### ISSUE TITLE
HMF search doesn't work for field parameters (degree, discriminant)

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#443]

**Comment by sanni85** [comment]
I will take a look into this now

**Comment by JohnCremona** [comment]
I already fixed this and there is a pull request open for TWO WEEKS which
has not been merged!!!!

**Comment by sanni85** [comment]
What I am looking at are the missing error parsing functionalities for the search boxes (type hello in the label search and you will see), I have just looked at your pull request (now merged) and I think this are still missing.

**Comment by JohnCremona** [comment]
On 28 October 2015 at 16:26, sanni85 <notifications@github.com> wrote:

> What I am looking at are the missing error parsing functionalities for the
> search boxes (type hello in the label search and you will see), I have just
> looked at your pull request (now m
>
Agreed.  But it still needs merging.

**Comment by davidfarmer** [comment]
I opened issue #547 , which may be related.

**Comment by JohnCremona** [comment]
OK, now there is nothing in this issue which is not covered by #547 so I am closing it.
